/*
 * MIT License
 * Copyright (c) 2019 Alon Rashelbach
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#pragma once

#include <time.h>
#include <bits/stdc++.h> // UINT_MAX
#include <set>
#include <array>

#include <basic_types.h>
#include <pipeline_thread.h>

#include <nuevomatch_base.h>
#include <nuevomatch_config.h>
#include <nuevomatch_workers.h>
#include <interval_set.h>

#include <cut_split.h>
#include <tuple_merge.h>
#include <rule_db.h>

/**
 * @brief NuevoMatch packet classifier main class, version 1.0
 *        Supports loading precompiled classifiers and running them.
 *        Supports multiple configurations and environments.
 * @tparam N Number of packets in batch
 */
template <uint32_t N>
class NuevoMatch : public GenericClassifier, public NuevoMatchWorkerListener<N> {
protected:

	typedef struct {
		classifier_output_t results[N];
		std::array<uint32_t, N> packet_id;
		volatile uint32_t lock;
		uint32_t counter;
		uint32_t valid_items;
	} reducer_job_t;

	// The configuration for this
	NuevoMatchConfig _configuration;

	// Pointers to all iSets
	IntervalSet<N>** _isets;

	// Workers
	NuevoMatchWorkerSerial<N>* _worker_serial;
	NuevoMatchWorkerParallel<N>** _workers_parallel;

	// Configuration for subset classifiers
	uint32_t _last_iset_idx;

	// Hold information
	uint32_t _num_of_isets;
	uint32_t _num_of_rules;
	uint32_t _size;
	uint32_t _build_time;

	// Used for packing
	uint8_t* _pack_buffer;
	uint32_t _pack_size;

	// Hold batches of input packets
	WorkBatch<const uint32_t*, N> _next_batch;
	uint32_t _next_batch_items;
	uint32_t _batch_counter;

	// Hold the results
	reducer_job_t* _reducer;

	// The remainder rules
	std::list<openflow_rule> _remainder_rules;

	// Performance
	struct timespec start_time, end_time;

	/**
	 * @brief Callback. Invoked by the iSet on result
	 * @param info The batch information generated by the iSet
	 * @param iset_index The iSet index
	 * @param batch_id A unique id for the batch
	 */
	virtual void on_new_result(WorkBatch<classifier_output_t, N> info, uint32_t iset_index, uint32_t batch_id);

public:

	/**
	 * @brief Initiate a new NuevoMatch instance.
	 * @param config The configuration for NuevoMatch
	 */
	NuevoMatch(NuevoMatchConfig config);
	virtual ~NuevoMatch();

	/**
	 * @brief Build the classifier data structure
	 * @returns 1 On success, 0 on fail
	 */
	int build(const std::list<openflow_rule>& rule_db) { warning("should be done with Python"); return 0; }

	/**
	 * @brief Packs this to byte array
	 * @returns An object-packer with the binary data
	 */
	ObjectPacker pack() const;

	/**
	 * @brief Creates this from a memory location
	 * @param object An object-reader instance
	 */
	void load(ObjectReader& object);

	/**
	 * @brief Returns the number of rules
	 */
	uint32_t get_num_of_rules() const {
		return _num_of_rules;
	}

	/**
	 * @brief Returns the memory size of this in bytes
	 */
	uint32_t get_size() const {
		return _size;
	}

	/**
	 * @brief Returns the building time of this in milliseconds
	 */
	uint32_t get_build_time() const {
		return _build_time;
	}

	/**
	 * @brief Returns the maximum supported number of fields this can classify
	 */
	virtual const unsigned int get_supported_number_of_fields() const { return UINT_MAX; }

	/**
	 * @brief Starts the performance measurement of this
	 */
	void start_performance_measurement();

	/**
	 * @brief Stops the performance measurement of this
	 */
	void stop_performance_measurement();

	/**
	 * @brief clones this to another instance
	 */
	virtual GenericClassifier* clone() {
		return new NuevoMatch(*this);
	}

	/**
	 * @brief Start an asynchronous process of classification for an input packet.
	 * @param header An array of 32bit integers according to the number of supported fields.
	 * @param priority The priority of a previous matching rule.
	 * Stops classifiying when there is no potential better priority
	 * @returns A unique id for the packet
	 */
	virtual unsigned int classify_async(const unsigned int* header, int priority);

	/**
	 * @brief Start a synchronous process of classification an input packet.
	 * @param header An array of 32bit integers according to the number of supported fields.
	 * @returns The matching rule action/priority (or 0xffffffff if not found)
	 */
	virtual unsigned int classify_sync(const unsigned int* header, int priority) {
		throw std::runtime_error("NuevoMatch can only perform asynchronous classification");
	}

	/**
	 * @brief Prints statistical information
	 * @param verbose Set the verbosity level of printing
	 */
	virtual void print(uint32_t verbose=1) const;

	/**
	 * @brief Resets the all classifier counters
	 */
	virtual void reset_counters();
	
	/**
         * @brief Advance the packet counter. Should be used when skipping 
         * classification of packets, such as with caches.
         */
        virtual void advance_counter();

	/**
	 * @brief Returns a string representation of this
	 */
	virtual const std::string to_string() const { return "NuevoMatch"; }


private:

	/**
	 * @brief Processes a new batch of packets. 
	 */
	void process_batch();

	/**
	 * @brief Loads all subsets (iSets/Remainder) from file
	 * @param reader An object-reader with binary data
	 */
	void load_subsets(ObjectReader& reader);

        /**
         * @brief Manually build remainder classifier
         */
        ObjectReader build_remainder();

	/**
	 * @brief Loads the remainder classifier from file
	 * @param reader An object-reader with binary data
	 */
	void load_remainder(ObjectReader& reader);

	/**
	 * @brief Group the subsets based on their size (load-balance), and assign them to cores
	 * @throws In case no valid subsets are available
	 */
	void group_subsets_to_cores();
};
